server:
  port: 8904
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8900/eureka/
spring:
  application:
    name: eurekaservice1
